# Permalinks
#
permalink:           pretty

# Setup
title:               ptb.io
tagline:             'ha ha made ya read!'
description:         'The personal website for Peter Travis Brown.'
url:                 http://ptb.io
baseurl:             ''

# About/contact
author:
  name:              Peter T. Brown
  url:               https://ptb.io
  email:             p@ptb.io

# Custom vars
version:             1.2.0